---
kind: pipeline
type: kubernetes
name: default

steps:
- name: clone_gh-pages
  image: plugins/git
  commands:
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git clone -b gh-pages --single-branch https://github.com/carpenike/helm-charts

- name: build
  image: dtzar/helm-kubectl:2.16.1
  commands:
  - helm init -c
  - helm lint nzbhydra
  - wget -O - https://github.com/norwoodj/helm-docs/releases/download/v0.8.0/helm-docs_0.8.0_Linux_x86_64.tar.gz | tar xvzf - helm-docs
  - ./helm-docs
  - helm package nzbhydra -d helm-charts
  - git --git-dir=./helm-charts/.git/ --work-tree=./helm-charts/ add -A 


- name: push_gh-pages
  image: appleboy/drone-git-push
  settings:
    remote: git@github.com:carpenike/helm-charts.git
    # remote_name: origin
    # branch: gh-pages
    # local_ref: gh-pages
    path: helm-charts
    key:
      from_secret: SSH_KEY
  # commands:
  # - git config --global user.email "drone@holthome.net"
  # - git config --global user.name "[Automation] Drone CI/CD"
  # - git --git-dir=/drone/src/helm-charts/.git/ --work-tree=/drone/src/helm-charts/ add -A
  # - git --git-dir=/drone/src/helm-charts/.git/ --work-tree=/drone/src/helm-charts/ commit -m "added additional file"
  # - git --git-dir=/drone/src/helm-charts/.git/ --work-tree=/drone/src/helm-charts/ push