---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: dtzar/helm-kubectl:2.16.1
  commands:
  - helm init -c
  - helm lint nzbhydra
  - wget -O - https://github.com/norwoodj/helm-docs/releases/download/v0.8.0/helm-docs_0.8.0_Linux_x86_64.tar.gz | tar xvzf - helm-docs
  - ./helm-docs
  - helm package nzbhydra
