---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: dtzar/helm-kubectl:2.16.1
  commands:
  - mkdir /tmp/nzbhydra
  - helm init -c
  - helm lint nzbhydra
  - wget -O - https://github.com/norwoodj/helm-docs/releases/download/v0.8.0/helm-docs_0.8.0_Linux_x86_64.tar.gz | tar xvzf - helm-docs
  - ./helm-docs
  - helm package nzbhydra -d /tmp/nzbhydra
  - ls /tmp/nzbhydra 

- name: clone_gh-pages
  image: alpine/git
  commands:
  - git clone -b gh-pages --single-branch https://github.com/carpenike/helm-charts /tmp/helm-charts
  - mv /tmp/nzbhydra/nzbhydra* /tmp/helm-charts
  - cd /tmp/helm-charts
  - ls /tmp
  - git add .
  - git commit -m "add updated helm package"
  - git push
